import { mkdir, readFile, writeFile, access } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { cappedThumbUrl, stripQuery, extFor, hashUrl } from "./lib/wikimedia-url.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const FULL_CAP_PX = 960;
// Photos live in a public GCS bucket (not in git). Local public/img is just a
// gitignored staging area that we rsync up to the bucket.
const GCS_BASE = "https://storage.googleapis.com/foray-field-guide/img";
const SOURCES = [
  path.join(ROOT, "lib/species-images.ts"),
  path.join(ROOT, "lib/tree-catalog.ts"),
  path.join(ROOT, "lib/species-gallery.ts"), // multi-photo ID galleries (Commons + iNaturalist)
];
// Staging lives OUTSIDE public/ so Next does not copy ~150MB into the export.
// We rsync this dir up to the GCS bucket; it is gitignored.
const THUMB_DIR = path.join(ROOT, ".image-staging/thumb");
const FULL_DIR = path.join(ROOT, ".image-staging/full");
const FORCE = process.argv.includes("--force");

// Hosts we self-host into GCS. Wikimedia gets a resized rendition via its
// thumbnailer; other hosts (e.g. iNaturalist) are downloaded as-is.
const URL_RE =
  /"(url|thumb)":"(https:\/\/(?:upload\.wikimedia\.org|inaturalist-open-data\.s3\.amazonaws\.com)\/[^"]+)"/g;

async function collectUrls() {
  const full = new Set();
  const thumb = new Set();
  for (const file of SOURCES) {
    let text;
    try {
      text = await readFile(file, "utf8");
    } catch {
      continue; // optional source (e.g. galleries not present yet)
    }
    for (const m of text.matchAll(URL_RE)) {
      const [, field, url] = m;
      (field === "thumb" ? thumb : full).add(url);
    }
  }
  return { full: [...full], thumb: [...thumb] };
}

async function exists(p) {
  try {
    await access(p, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

const UA = "ForayFieldGuide/1.0 (info@gocapsule.ai) offline-field-guide";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function download(url, destAbs, attempt = 0) {
  if (!FORCE && (await exists(destAbs))) return true;
  let res;
  try {
    res = await fetch(url, { headers: { "User-Agent": UA } });
  } catch {
    if (attempt < 4) {
      await sleep(500 * 2 ** attempt);
      return download(url, destAbs, attempt + 1);
    }
    return false;
  }
  if (res.status === 429 || res.status === 503) {
    if (attempt < 5) {
      const retryAfter = Number.parseInt(res.headers.get("retry-after") ?? "", 10);
      const wait = Number.isFinite(retryAfter) ? retryAfter * 1000 : 800 * 2 ** attempt;
      await sleep(wait);
      return download(url, destAbs, attempt + 1);
    }
    return false;
  }
  if (!res.ok) return false;
  const buf = Buffer.from(await res.arrayBuffer());
  await writeFile(destAbs, buf);
  await sleep(120); // politeness between successful downloads
  return true;
}

function localName(url) {
  const ext = extFor(url) === "svg" ? "png" : extFor(url);
  return `${hashUrl(stripQuery(url))}.${ext}`;
}

async function main() {
  await mkdir(THUMB_DIR, { recursive: true });
  await mkdir(FULL_DIR, { recursive: true });
  const { full, thumb } = await collectUrls();
  console.log(`Collected ${thumb.length} thumb URLs, ${full.length} full URLs.`);
  const map = {};
  const fullPaths = [];
  let ok = 0;
  let failed = 0;

  for (const url of thumb) {
    const name = localName(url);
    const dest = path.join(THUMB_DIR, name);
    let got = await download(stripQuery(url), dest);
    if (!got) {
      // Some catalog `thumb` values are malformed renditions (HTTP 400).
      // Fall back to a cleanly-derived 330px rendition of the same file.
      const derived = cappedThumbUrl(url, 330);
      if (derived) got = await download(derived, dest);
    }
    if (got) {
      map[url] = `${GCS_BASE}/thumb/${name}`;
      ok++;
    } else {
      failed++;
      console.warn("thumb FAIL", url);
    }
  }

  for (const url of full) {
    const name = localName(url);
    const dest = path.join(FULL_DIR, name);
    const capped = cappedThumbUrl(url, FULL_CAP_PX);
    let got = capped ? await download(capped, dest) : false;
    if (!got) got = await download(stripQuery(url), dest); // fallback to original
    if (got) {
      map[url] = `${GCS_BASE}/full/${name}`;
      fullPaths.push(`${GCS_BASE}/full/${name}`);
      ok++;
    } else {
      failed++;
      console.warn("full FAIL", url);
    }
  }

  const allUrls = [...new Set(Object.values(map))].sort();
  const entries = Object.keys(map)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
    .join("\n");
  const out = `// AUTO-GENERATED by scripts/localize-images.mjs. Do not edit by hand.
// Maps remote Wikimedia URLs (as they appear in the catalogs) to the public
// GCS bucket URLs we self-host for offline use.
export const LOCAL_IMAGES: Record<string, string> = {
${entries}
};

// Every self-hosted photo URL (thumbnails + full), warmed into the offline
// cache in the background after first online load.
export const OFFLINE_IMAGE_URLS: string[] = ${JSON.stringify(allUrls, null, 2)};
`;
  await writeFile(path.join(ROOT, "lib/local-images.ts"), out);
  console.log(
    `Localized ${ok} images (${failed} failed). Map: ${Object.keys(map).length} entries, ${allUrls.length} URLs.`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
