// AUTO-GENERATED by scripts/lookalikes/codegen-synthesized.mjs. Do not edit by hand.
// PENDING HUMAN REVIEW — toxic/deadly/psychoactive species held out of the live
// catalog. Not imported anywhere until individually approved.
import type { MushroomSpecies } from "../../species-types";

export const PENDING_SPECIES: MushroomSpecies[] = [

];
