// AUTO-GENERATED by scripts/lookalikes/codegen-synthesized.mjs. Do not edit by hand.
// PENDING HUMAN REVIEW — toxic/deadly/psychoactive species held out of the live
// catalog. Not imported anywhere until individually approved.
import type { MushroomSpecies } from "../../species-types";

export const PENDING_SPECIES: MushroomSpecies[] = [
  {
    id: "amanita-velatipes",
    commonNames: [
      "Veiled-bulb Amanita",
      "Great Funnel-Veil Amanita"
    ],
    scientific: "Amanita velatipes",
    family: "Amanitaceae",
    order: "Agaricales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented.",
    habitat: "A species of Amanita from eastern North America; it is NOT recorded from the Pacific Northwest.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented.",
      underside: "Not documented.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "Flagged as toxic; specific toxins and effects are not documented in the source.",
    lookalikes: [],
    culinary: {
      flavor: "Not documented.",
      preparation: "Not documented.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Amanita velatipes",
        url: "https://en.wikipedia.org/wiki/Amanita_velatipes"
      },
      {
        name: "iNaturalist — Amanita velatipes",
        url: "https://www.inaturalist.org/taxa/350068"
      },
      {
        name: "GBIF — Amanita velatipes",
        url: "https://www.gbif.org/species/5451757"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "disputed",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); Wikipedia extract is a stub with minimal description and no documented toxins; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "boletus-pulcherrimus",
    commonNames: [
      "Red-pored Bolete"
    ],
    scientific: "Rubroboletus pulcherrimus",
    family: "Boletaceae",
    order: "Boletales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: [
      "Lithocarpus",
      "Pseudotsuga",
      "Abies"
    ],
    hostTrees: [
      {
        common: "Tanbark oak",
        scientific: "Lithocarpus densiflora"
      },
      {
        common: "Douglas-fir",
        scientific: "Pseudotsuga menziesii"
      },
      {
        common: "Grand fir",
        scientific: "Abies grandis"
      }
    ],
    substrate: "Grows in humus in mixed woodlands; associated with forests containing tanbark oak, Douglas-fir, and grand fir. Increased fruitings reported after warm heavy fall rains following a humid summer.",
    habitat: "Found in western North America, from New Mexico and California to Washington, and may feasibly occur in British Columbia, Canada. Fruits in autumn, singly or in groups, in humus in mixed woodlands; one source notes it grows at low altitudes in the Cascade Range and Olympic Mountains while another claims high elevations over about 1,500 m.",
    elevationM: {
      min: 0,
      max: 1500
    },
    regionsPNW: [
      "Washington Cascades",
      "Olympic Peninsula",
      "Western Washington",
      "Northern California",
      "Coastal British Columbia"
    ],
    fruitingMonths: [
      9,
      10,
      11
    ],
    peakMonths: [
      9,
      10,
      11
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Olive- to reddish-brown in various shades, convex becoming flattened, sometimes reaching 25 cm in diameter and 3-4 cm thick; surface smooth or velvety when young, may be scaled in older specimens; margin inrolled when young, rolling out and flattening with age.",
      underside: "Adnate poroid surface bright red to dark red or red-brown, bruising dark blue or black; 2-3 pores per mm when young, expanding to 1-2 per mm at maturity, angular pores up to 1 mm; tubes 0.5-1.5 cm long, yellow in cross section.",
      stem: "Solid and firm, 7-20 cm long and up to 10 cm thick at the base, tapering to 2-5 cm at the top; yellow or yellow-brown, bearing a network of red reticulations on the upper two-thirds.",
      fleshColor: "Yellow (tubes and flesh yellow in cross section); pores stain blue when cut or bruised.",
      sporePrintColor: "Olive-brown; spores spindle-shaped or elliptical, thick-walled, smooth, 13-16 by 5.5-6.5 micrometres.",
      odor: "Indistinct, or slightly fragrant; taste reportedly mild.",
      sizeCm: "Cap up to 25 cm diameter; stem 7-20 cm long x up to 10 cm thick."
    },
    edibility: "toxic",
    toxicityNotes: "Poisonous and potentially fatal, implicated in at least one death: in 1994 a couple developed gastrointestinal symptoms after eating it and the husband died, with autopsy revealing an infarction of the midgut. Known to contain low levels of muscarine, a peripheral nervous system toxin. In general, blue-staining red-pored boletes should be avoided; severe gastrointestinal symptoms were reported in a person who had merely tasted it.",
    lookalikes: [
      {
        name: "Eastwood's bolete",
        scientific: "Rubroboletus eastwoodiae",
        danger: "toxic",
        distinguishingFeature: "Superficially similar but has a much thicker stalk."
      },
      {
        name: "Rubroboletus haematinus",
        scientific: "Rubroboletus haematinus",
        danger: "inedible",
        distinguishingFeature: "Distinguished by its yellower stem and cap colours that are various shades of brown."
      },
      {
        name: "Satan's bolete",
        scientific: "Rubroboletus satanas",
        danger: "toxic",
        distinguishingFeature: "Differentiated from R. pulcherrimus by R. pulcherrimus's darker cap and lack of reticulation on the stipe (relative to satanas)."
      },
      {
        name: "Neoboletus luridiformis",
        scientific: "Neoboletus luridiformis",
        danger: "edible-when-cooked",
        distinguishingFeature: "Grows with oaks but is smaller and has a non-reticulate stipe."
      }
    ],
    culinary: {
      flavor: "Taste reportedly mild, odor indistinct or slightly fragrant; however the species is poisonous and must not be eaten.",
      preparation: "Do not consume; poisonous and potentially fatal. Blue-staining red-pored boletes should be avoided.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Rubroboletus pulcherrimus",
        url: "https://en.wikipedia.org/wiki/Rubroboletus_pulcherrimus"
      },
      {
        name: "iNaturalist — Rubroboletus pulcherrimus",
        url: "https://www.inaturalist.org/taxa/790951"
      },
      {
        name: "GBIF — Boletus pulcherrimus",
        url: "https://www.gbif.org/species/6016446"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; sources disagree on elevation (low altitude vs over 1,500 m) and on whether it fruits in groups; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "cortinarius-gentilis",
    commonNames: [
      "Goldband Webcap",
      "Conifer Webcap"
    ],
    scientific: "Cortinarius gentilis",
    family: "Cortinariaceae",
    order: "Agaricales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: [
      "Conifers"
    ],
    hostTrees: [
      {
        common: "Conifer",
        scientific: "Pinophyta"
      }
    ],
    substrate: "Growing in moss under conifer trees, separately or in groups. Ectomycorrhizal.",
    habitat: "A fungus of the subgenus Telamonia found growing separate or in groups in moss under conifer trees. Normally found in North America and Europe, including North America's Pacific Northwest and Rocky Mountains.",
    elevationM: null,
    regionsPNW: [
      "Washington Cascades",
      "Western Washington",
      "Western Oregon"
    ],
    fruitingMonths: [
      9,
      10,
      11
    ],
    peakMonths: [
      9,
      10
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Bright tan, umbonate, 1-5 cm wide.",
      underside: "Gills distant, similarly coloured to the cap but sometimes reddish with age.",
      stem: "Up to 10 cm long, resembling a root, with yellow veil remnants near the bottom.",
      fleshColor: "Tan.",
      sporePrintColor: "Rusty-brown.",
      odor: "Of raw potatoes.",
      sizeCm: "Cap 1-5 cm wide; stem up to 10 cm long."
    },
    edibility: "inedible",
    toxicityNotes: "Toxicity is disputed. In the 20th century it was considered poisonous in Finnish mycological publications (and deadly by mycologist David Arora), reported to belong to subgenus Leprocybe and to contain the toxin orellanine, but these details have since been disputed. The claim of toxicity primarily stemmed from Mottonen et al. (1975) and a case study by Hulmi et al. (1975); a specimen from the former study, when reexamined, turned out to be the highly toxic C. speciosissimus. A 2003 Finnish study analysed 28 samples and an unspecific cell-culture toxicity test and a mouse feeding test revealed no signs of toxicity. Not recommended for the table given the genus's history and confusion with deadly orellanine-containing webcaps.",
    lookalikes: [
      {
        name: "Cortinarius speciosissimus",
        scientific: "Cortinarius speciosissimus",
        danger: "deadly",
        distinguishingFeature: "A highly toxic webcap; a specimen labelled C. gentilis in an early toxicity study was reexamined and found to actually be this species, underscoring the risk of confusion within the genus."
      }
    ],
    culinary: {
      flavor: "Not documented.",
      preparation: "Not recommended; treated as inedible owing to disputed toxicity and confusion with deadly relatives.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Cortinarius gentilis",
        url: "https://en.wikipedia.org/wiki/Cortinarius_gentilis"
      },
      {
        name: "iNaturalist — Cortinarius gentilis",
        url: "https://www.inaturalist.org/taxa/335624"
      },
      {
        name: "GBIF — Cortinarius gentilis",
        url: "https://www.gbif.org/species/2529240"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates. Historical toxicity claims (orellanine) disputed; a 2003 study found no toxicity, but treated as inedible due to genus confusion."
    }
  },
  {
    id: "gyromitra-ancilis",
    commonNames: [
      "Pig's ears"
    ],
    scientific: "Gyromitra ancilis",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented",
    habitat: "Not documented",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented",
      underside: "Not documented",
      stem: "Not documented",
      fleshColor: "Not documented",
      sporePrintColor: "Not documented",
      odor: "Not documented",
      sizeCm: "Not documented"
    },
    edibility: "toxic",
    toxicityNotes: "As a Gyromitra species, this fungus is associated with the toxin gyromitrin (which hydrolyses to monomethylhydrazine); it should be treated as toxic and at best edible only when properly cooked. Detailed toxicity data is not documented in the cached sources.",
    lookalikes: [],
    culinary: {
      flavor: "Not documented",
      preparation: "Not documented",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "iNaturalist — Discina ancilis",
        url: "https://www.inaturalist.org/taxa/504623"
      },
      {
        name: "GBIF — Gyromitra ancilis",
        url: "https://www.gbif.org/species/8933807"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-22",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; identification/ecology source-derived; conditions are genus/habitat-typical estimates, not field-measured."
    }
  },
  {
    id: "gyromitra-gigas",
    commonNames: [
      "Snow mushroom",
      "Snowbank false morel",
      "Snow morel",
      "Snow false morel",
      "Giant's false morel",
      "Calf brain",
      "Bull nose",
      "Walnut"
    ],
    scientific: "Gyromitra gigas",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented in detail; a false morel that fruits in spring and early summer in habitats similar to true morels (Morchella ssp.).",
    habitat: "A false morel found in Europe, so named for its resemblance to and shared spring/early-summer occurrence with true morels (Morchella ssp.) in similar habitats. NOT recorded from the Pacific Northwest (documented from Europe; a very similar, directly related North American species is D. montana).",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [
      4,
      5,
      6,
      7
    ],
    peakMonths: [
      5
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Tannish, wrinkled, brain-like (convoluted/saddle-like) cap growing up to 10 cm (4 in) broad and 6 cm tall; characteristic of the false morels in resembling true morels.",
      underside: "Not documented; the wrinkled, convoluted cap is the fertile (spore-bearing) surface rather than gills or pores.",
      stem: "Whitish stalk, typically almost as thick as the cap, up to 10 cm long and broad.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented; D. montana reportedly has larger spores than D. gigas.",
      odor: "Not documented.",
      sizeCm: "Cap up to 10 cm broad and 6 cm tall; stalk up to 10 cm long and broad."
    },
    edibility: "toxic",
    toxicityNotes: "Contains small quantities of hydrazines; gyromitrin content was assessed by Viernstein et al. (1980) at about 1 mg per kg of fresh mushroom (roughly 1,500-fold less than Gyromitra esculenta). No casualties have been ascribed to its consumption and some guides list it as edible if properly prepared, but parboiling is still highly recommended and consumption is not advised owing to variability and similarity to more toxic Gyromitra species. Banned for sale in France since 1991 due to potential toxicity, the effects of which would cause a rare fatal neurodegenerative disease, amyotrophic lateral sclerosis (ALS).",
    lookalikes: [
      {
        name: "Snow morel (North American)",
        scientific: "Discina montana",
        danger: "toxic",
        distinguishingFeature: "A very similar and directly related species occurring in North America; it apparently has larger spores than D. gigas. Both are reportedly edible in small amounts if thoroughly cooked, but eating is not recommended due to similarity to more toxic mushroom species."
      },
      {
        name: "True morels",
        scientific: "Morchella ssp.",
        danger: "edible",
        distinguishingFeature: "D. gigas is one of the false morels, resembling true morels and occurring in the spring and early summer in similar habitats; its cap is wrinkled/convoluted (brain-like) rather than the pitted, honeycombed cap of true Morchella."
      }
    ],
    culinary: {
      flavor: "Not documented.",
      preparation: "Reportedly edible in small amounts only if thoroughly cooked; parboiling is highly recommended. Consumption is not recommended due to variability in toxin content and similarity to more toxic Gyromitra species.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Discina gigas",
        url: "https://en.wikipedia.org/wiki/Discina_gigas"
      },
      {
        name: "iNaturalist — Giant's False Morel (Maublancomyces gigas)",
        url: "https://www.inaturalist.org/taxa/1613049"
      },
      {
        name: "GBIF — Gyromitra gigas",
        url: "https://www.gbif.org/species/12197740"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "gyromitra-infula",
    commonNames: [
      "Hooded false morel",
      "Elfin saddle",
      "Saddle-shaped false morel"
    ],
    scientific: "Gyromitra infula",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [
      {
        common: "White spruce",
        scientific: "Picea glauca"
      },
      {
        common: "Black spruce",
        scientific: "Picea mariana"
      },
      {
        common: "Sitka spruce",
        scientific: "Picea sitchensis"
      },
      {
        common: "Lodgepole pine",
        scientific: "Pinus contorta"
      },
      {
        common: "Jack pine",
        scientific: "Pinus banksiana"
      },
      {
        common: "Western white pine",
        scientific: "Pinus monticola"
      },
      {
        common: "Balsam fir",
        scientific: "Abies balsamea"
      },
      {
        common: "Grand fir",
        scientific: "Abies grandis"
      },
      {
        common: "Douglas-fir",
        scientific: "Pseudotsuga menziesii"
      },
      {
        common: "Western hemlock",
        scientific: "Tsuga heterophylla"
      },
      {
        common: "Western larch",
        scientific: "Larix occidentalis"
      },
      {
        common: "Western red cedar",
        scientific: "Thuja plicata"
      },
      {
        common: "Balsam poplar",
        scientific: "Populus balsamifera"
      },
      {
        common: "Quaking aspen",
        scientific: "Populus tremuloides"
      },
      {
        common: "Bigleaf maple",
        scientific: "Acer macrophyllum"
      },
      {
        common: "Alder",
        scientific: "Alnus species"
      },
      {
        common: "Paper birch",
        scientific: "Betula papyrifera"
      }
    ],
    substrate: "Rotting wood or hard-packed ground; commonly found on packed ground such as beside country roads or in campgrounds. Grows in or near coniferous woodland, often on rotten wood.",
    habitat: "Widely distributed throughout boreal, montane and coastal forests in North America; the North American range extends north to Canada and south to Mexico, and it has also been reported from South America, Europe and Asia. Found growing singly to scattered in or near coniferous woodland in autumn, often on rotten wood or on packed ground. Associated conifers include Sitka spruce, Douglas-fir, western hemlock and western red cedar, placing it within Pacific Northwest forests.",
    elevationM: null,
    regionsPNW: [
      "Puget Sound lowlands",
      "Vancouver Island",
      "Oregon Coast Range",
      "Olympic Peninsula",
      "Washington Cascades",
      "Coastal British Columbia",
      "Western Washington",
      "Western Oregon"
    ],
    fruitingMonths: [
      8,
      9,
      10,
      11
    ],
    peakMonths: [
      9,
      10,
      11
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Apothecium about 2.5-9 cm (1-3.5 in) wide and tall, dark reddish to orangish brown, saddle-shaped with 2-4 lobes; the ends of the saddle lobes are drawn out to sharp tips that project above the fruit body. Wavy or bumpy rather than brain-like; chambered or hollow within and frequently develops blackish-brown spots. (As a false morel in the Gyromitra group, note the saddle/brain-like cap and the gyromitrin association of the group.)",
      underside: "Not gills: the fertile spore-bearing surface (hymenium) is on the outside of the cap; as the cap periphery joins the stipe it forms a hollow, roughly bell-shaped structure with the hymenium arching into folds and pads.",
      stem: "Mostly hollow stipe, 2-8 cm high and 1-2.5 cm thick, reddish brown to whitish or even bluish but typically lighter than the cap; smooth on the outside, minutely tomentose (covered with very fine hairs), hollow with some chambers inside.",
      fleshColor: "Context (flesh) 1-2 mm thick, brittle, whitish to brownish.",
      sporePrintColor: "Ascospores hyaline (colorless); ellipsoidal, smooth, thin-walled, 17-22 by 7-9 μm, biguttulate with two large oil droplets.",
      odor: "Lacks a notable odor or taste.",
      sizeCm: "Cap 2.5-9 cm wide and tall; stipe 2-8 cm high by 1-2.5 cm thick."
    },
    edibility: "toxic",
    toxicityNotes: "Long and widely regarded as poisonous and believed to contain the toxic compound gyromitrin (present in some Gyromitra species), which when digested is metabolized into monomethylhydrazine, a major component of rocket fuel. However, a 2023 study found no traces of gyromitrin in G. infula (now Paragyromitra infula) using a new chromatography method, throwing the long-held poisonous status into doubt. Treated as toxic pending resolution of this dispute, given its membership in the gyromitrin-associated false morel group and historical classification as poisonous.",
    lookalikes: [
      {
        name: "Brain mushroom (false morel)",
        scientific: "Gyromitra esculenta",
        danger: "toxic",
        distinguishingFeature: "Has a wrinkled surface with brain-like convolutions, not wavy or bumpy like P. infula."
      },
      {
        name: "Paragyromitra ambigua",
        scientific: "Paragyromitra ambigua",
        danger: "toxic",
        distinguishingFeature: "Very similar in appearance and usually not distinguishable without microscopy; said to have more pronounced purple tints in the stipe and larger spores (about 22-30 μm long)."
      },
      {
        name: "Discina brunnea",
        scientific: "Discina brunnea",
        danger: "edible-with-caution",
        distinguishingFeature: "More stout with a white stem and a wrinkled cap that usually lacks points."
      },
      {
        name: "Elfin saddles",
        scientific: "Helvella species",
        danger: "inedible",
        distinguishingFeature: "The saddle-shaped cap can cause confusion, but Helvella species typically have grayer colors and thinner, fluted stipes (e.g. H. maculata, which has distinctly white flesh)."
      }
    ],
    culinary: {
      flavor: "Lacks a notable taste.",
      preparation: "Not recommended for consumption; historically regarded as poisonous owing to suspected gyromitrin content, although a 2023 study found no gyromitrin.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Paragyromitra infula",
        url: "https://en.wikipedia.org/wiki/Paragyromitra_infula"
      },
      {
        name: "iNaturalist — Saddle-shaped False Morel (Paragyromitra infula)",
        url: "https://www.inaturalist.org/taxa/1613028"
      },
      {
        name: "GBIF — Gyromitra infula",
        url: "https://www.gbif.org/species/5258509"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "gyromitra-korfii",
    commonNames: [
      "Not documented"
    ],
    scientific: "Gyromitra korfii",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented (no species-level cached source; only the genus Gyromitra page is available).",
    habitat: "Not documented at the species level in the cached sources. Gyromitra is a genus of about 18 species of ascomycete false morels; species-specific habitat for G. korfii is not documented here.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented at species level; Gyromitra are false morels whose cap is typically convoluted and turban- or brain-like (the genus name derives from gyro, convoluted, and mitra, turban). Members of this gyromitrin-associated false morel group can be mistaken for true morels (Morchella).",
      underside: "Not documented; the convoluted cap surface is the fertile (spore-bearing) layer rather than gills or pores.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "No species-specific toxicity data in the cached sources; assessed from the genus. Some species of Gyromitra are highly poisonous when eaten raw due to the presence of gyromitrin, although some are edible when cooked and Gyromitra spp. are sought after in Scandinavian countries. Widespread hemolysis has been reported from ingestion, which can result in kidney failure; methemoglobinemia has also been seen (typically responsive to methylene blue); and seizures can develop via inhibition of the neurotransmitter GABA. Treated as toxic given the gyromitrin association of the genus, pending species-level review.",
    lookalikes: [
      {
        name: "True morels",
        scientific: "Morchella",
        danger: "edible",
        distinguishingFeature: "Gyromitra are false morels that can be mistaken for the edible true morels (Morchella); the convoluted, turban-like Gyromitra cap differs from the pitted, honeycombed cap of true morels."
      }
    ],
    culinary: {
      flavor: "Not documented.",
      preparation: "Not recommended; some Gyromitra are highly poisonous raw due to gyromitrin, and species-level preparation data for G. korfii is not documented.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Gyromitra (genus)",
        url: "https://en.wikipedia.org/wiki/Gyromitra"
      },
      {
        name: "iNaturalist — Maublancomyces korfii",
        url: "https://www.inaturalist.org/taxa/1613047"
      },
      {
        name: "GBIF — Gyromitra korfii",
        url: "https://www.gbif.org/species/5497497"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "gyromitra-montana",
    commonNames: [
      "Mountain Lorchel",
      "Snow morel (North American)"
    ],
    scientific: "Gyromitra montana",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented in detail; a false morel of the Discina/Gyromitra group that fruits in spring and early summer (snowmelt) in habitats similar to true morels.",
    habitat: "Occurs in North America; described as a very similar, directly related species to the European Discina gigas, from which it apparently differs in having larger spores. As a member of the Discina genus (related to the false morels of Gyromitra), it bears dish- or cup-shaped to convoluted fruit bodies. Species-level distribution within the cached sources notes only North America (Mountain Lorchel); finer PNW localities are not documented.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [
      4,
      5,
      6,
      7
    ],
    peakMonths: [
      5
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented in detail at species level; as a Discina/false-morel relative of Gyromitra the fruit body is dish- or cup-shaped to wrinkled and convoluted (brain-like), resembling true morels. Reportedly very similar to Discina gigas (tannish, wrinkled cap), differing chiefly in spore size.",
      underside: "Not gills: the wrinkled/cup-shaped upper surface is the fertile spore-bearing layer.",
      stem: "Not documented at species level; the related D. gigas has a whitish stalk nearly as thick as the cap.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented; spores apparently larger than those of Discina gigas.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "No species-specific toxin assay in the cached sources. As a Discina relative of the highly toxic false morels of Gyromitra, it is viewed with suspicion (the genus Discina is related to false morels; the best-known member, the pig ear D. ancilis, is deemed edible only after thorough cooking yet viewed with suspicion given the relation to highly toxic false morels). Like the directly related Discina gigas, it is reportedly edible in small amounts only if thoroughly cooked, but eating is not recommended due to similarity to more toxic Gyromitra species. Treated as toxic owing to the gyromitrin-associated false-morel group, pending species-level review.",
    lookalikes: [
      {
        name: "Snow false morel",
        scientific: "Discina gigas",
        danger: "toxic",
        distinguishingFeature: "A very similar and directly related European species; D. montana apparently has larger spores than D. gigas. Both are reportedly edible in small amounts only if thoroughly cooked, but eating is not recommended due to similarity to more toxic mushroom species."
      },
      {
        name: "Pig's ear",
        scientific: "Discina ancilis",
        danger: "edible-when-cooked",
        distinguishingFeature: "The best-known Discina, bearing dish- or cup-shaped fruit bodies; deemed edible after thorough cooking but viewed with suspicion given its relation to the highly toxic false morels."
      },
      {
        name: "True morels",
        scientific: "Morchella",
        danger: "edible",
        distinguishingFeature: "Discina and Gyromitra are false morels related to and resembling true morels; the wrinkled/convoluted or cup-shaped cap differs from the pitted, honeycombed cap of true Morchella."
      }
    ],
    culinary: {
      flavor: "Not documented.",
      preparation: "Reportedly edible in small amounts only if thoroughly cooked, but consumption is not recommended due to similarity to more toxic Gyromitra species.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Discina (fungus)",
        url: "https://en.wikipedia.org/wiki/Discina_(fungus)"
      },
      {
        name: "iNaturalist — Mountain Lorchel (Maublancomyces montanus)",
        url: "https://www.inaturalist.org/taxa/1613046"
      },
      {
        name: "GBIF — Gyromitra montana",
        url: "https://www.gbif.org/species/5497502"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "lactarius-xanthogalactus",
    commonNames: [
      "Yellow-staining Milkcap",
      "Yellow-staining Milk Cap"
    ],
    scientific: "Lactarius xanthogalactus",
    family: "Russulaceae",
    order: "Russulales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Grows on the ground under trees (both conifers and hardwoods). Ectomycorrhizal genus.",
    habitat: "Found on the west coast of the United States, growing on the ground under trees. Fruit bodies grow scattered or in groups under conifers and hardwoods between November and February in Oregon and California.",
    elevationM: null,
    regionsPNW: [
      "Western Oregon",
      "Oregon Coast Range"
    ],
    fruitingMonths: [
      11,
      12,
      1,
      2
    ],
    peakMonths: [
      11,
      12
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Pinkish-cinnamon, measuring 3-11 cm (1.25-4.25 in) wide.",
      underside: "Gills that, with the rest of the mushroom, ooze a white latex when cut or injured that rapidly turns bright sulfur-yellow.",
      stem: "Pinkish-white, 2-6 cm (0.75-2.25 in) long and 0.7-2 cm (0.25-0.75 in) wide.",
      fleshColor: "Exudes white latex that rapidly turns bright sulfur-yellow when cut or injured.",
      sporePrintColor: "Pale yellow.",
      odor: "Not documented.",
      sizeCm: "Cap 3-11 cm wide; stem 2-6 x 0.7-2 cm."
    },
    edibility: "toxic",
    toxicityNotes: "Poisonous. The mushroom has an unpleasant taste. Specific toxins are not documented in the source.",
    lookalikes: [
      {
        name: "Lactarius vinaceorufescens",
        scientific: "Lactarius vinaceorufescens",
        danger: "toxic",
        distinguishingFeature: "Nearly identical microscopic features to L. xanthogalactus, but macroscopically it has reddish-vinaceous stains that develop on the cap, gills, and stem."
      },
      {
        name: "Lactarius colorascens",
        scientific: "Lactarius colorascens",
        danger: "inedible",
        distinguishingFeature: "Distinguished by a smaller fruit body; a whitish cap that becomes brownish-red with age and does not spot vinaceous or brown; bitter to faintly acrid latex; and slightly smaller spores."
      },
      {
        name: "Lactarius chrysorrheus",
        scientific: "Lactarius chrysorrheus",
        danger: "toxic",
        distinguishingFeature: "Has a whitish to pale yellowish-cinnamon cap with slightly darker spots and grows under hardwoods (especially oak) on well-drained, often sandy soil; its gills do not discolor or spot vinaceous or brown."
      },
      {
        name: "Lactarius rubidus",
        scientific: "Lactarius rubidus",
        danger: "edible",
        distinguishingFeature: "Redder and sweet smelling, lacking the yellow staining reaction characteristic of L. xanthogalactus."
      }
    ],
    culinary: {
      flavor: "Unpleasant taste.",
      preparation: "Poisonous; not for consumption.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Lactarius xanthogalactus",
        url: "https://en.wikipedia.org/wiki/Lactarius_xanthogalactus"
      },
      {
        name: "iNaturalist — Lactarius xanthogalactus",
        url: "https://www.inaturalist.org/taxa/118224"
      },
      {
        name: "GBIF — Lactarius xanthogalactus",
        url: "https://www.gbif.org/species/5463015"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "lepiota-cristata",
    commonNames: [
      "Stinking Dapperling",
      "Brown-eyed Parasol",
      "Stinking Parasol",
      "Malodorous Lepiota",
      "Burnt-rubber Lepiota"
    ],
    scientific: "Lepiota cristata",
    family: "Agaricaceae",
    order: "Agaricales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Saprobic, deriving nutrients by decomposing dead or decayed organic material; observed on the soil of broadleaved and conifer (Pinopsida) trees, garden waste, leaf litter, and disturbed ground.",
    habitat: "Fruits on the ground in disturbed areas, such as lawns, path and road edges, parks, and gardens; also woodlands, shady and damp gardens, short grass, leaf litter, paths, and ditches. Grows singly or in small groups. One of the most widely distributed Lepiota species, found in North America (north of Mexico), throughout Europe, northern Asia, and New Zealand.",
    elevationM: null,
    regionsPNW: [
      "Puget Sound lowlands",
      "Willamette Valley",
      "Western Washington",
      "Western Oregon"
    ],
    fruitingMonths: [
      6,
      7,
      8,
      9,
      10,
      11
    ],
    peakMonths: [
      9,
      10
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "White to cream base colour covered with concentrically arranged reddish-brown scales, the center darker reddish-brown; 1-5 cm (0.4-2.0 in) across at maturity. Initially bell-shaped to convex, later flattening and developing an umbo.",
      underside: "Crowded gills, white to cream, free from the stipe, darkening and becoming brownish as the mushroom ages and spores mature.",
      stem: "2-6 cm (0.8-2.4 in) long and 0.2-0.7 cm (0.1-0.3 in) thick, nearly smooth, pale white-tinged, with a transient membranous and deciduous ring.",
      fleshColor: "Thin and white.",
      sporePrintColor: "White (greyish green in the variety L. cristata var. viridispora).",
      odor: "Strong, distinctive and unpleasant; described as rubbery (resembling burnt rubber), fishy, pungent, foul, fungusy, fruity, mealy and sweet.",
      sizeCm: "Cap 1-5 cm across; stem 2-6 x 0.2-0.7 cm."
    },
    edibility: "toxic",
    toxicityNotes: "Regarded as suspect by mycologists; it may be poisonous, with suspicion arising because many other small Lepiota species are poisonous. It has been said to cause gastrointestinal symptoms. Historic confusion with edible parasols (Macrolepiota) may have added to poisoning incidence. Specific toxins are not documented in the source.",
    lookalikes: [
      {
        name: "Lepiota ignivolvata",
        scientific: "Lepiota ignivolvata",
        danger: "inedible",
        distinguishingFeature: "Has a bright orange or red-brown ring low down on the stipe."
      },
      {
        name: "Lepiota lilacea",
        scientific: "Lepiota lilacea",
        danger: "toxic",
        distinguishingFeature: "Rare, toxic species with a morphology similar to L. cristata but with purple to purple-brown colours."
      },
      {
        name: "Lepiota saponella",
        scientific: "Lepiota saponella",
        danger: "inedible",
        distinguishingFeature: "Found on the west coast of France; distinguished by a soapy smell, dingy buff-coloured gills, smaller cap scales, and more triangular spores."
      },
      {
        name: "False parasol",
        scientific: "Chlorophyllum molybdites",
        danger: "toxic",
        distinguishingFeature: "Has a greyish-green spore print, similar to L. cristata var. viridispora; ordinary L. cristata has a white spore print."
      }
    ],
    culinary: {
      flavor: "Described as having a mild and pleasant taste despite its strong unpleasant odour.",
      preparation: "Suspect/possibly poisonous; not for consumption.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Lepiota cristata",
        url: "https://en.wikipedia.org/wiki/Lepiota_cristata"
      },
      {
        name: "iNaturalist — Lepiota cristata",
        url: "https://www.inaturalist.org/taxa/58694"
      },
      {
        name: "GBIF — Lepiota cristata",
        url: "https://www.gbif.org/species/2535471"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "paxillus-rubicundulus",
    commonNames: [
      "Alder Rollrim"
    ],
    scientific: "Paxillus rubicundulus",
    family: "Paxillaceae",
    order: "Boletales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: [
      "Alnus"
    ],
    hostTrees: [
      {
        common: "Alder",
        scientific: "Alnus"
      }
    ],
    substrate: "Not documented.",
    habitat: "Not documented in the available source. Common name (alder rollrim) indicates association with alder.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [
      9,
      10,
      11
    ],
    peakMonths: [
      9,
      10
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented.",
      underside: "Not documented.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "Genus Paxillus is documented as toxic to deadly; species-specific toxins and effects are not documented in the available source. Paxillus species are associated with an immune-mediated (autoimmune) haemolytic toxicity.",
    lookalikes: [],
    culinary: {
      flavor: "Not documented.",
      preparation: "Toxic; not for consumption.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "iNaturalist — Paxillus rubicundulus",
        url: "https://www.inaturalist.org/taxa/496729"
      },
      {
        name: "GBIF — Paxillus rubicundulus",
        url: "https://www.gbif.org/species/5239994"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 2,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from iNaturalist/GBIF (Wikipedia source unavailable); PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "paxillus-vernalis",
    commonNames: [],
    scientific: "Paxillus vernalis",
    family: "Paxillaceae",
    order: "Boletales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented; found in montane forests.",
    habitat: "A basidiomycete fungus found in montane forests in northern North America.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented. Closely resembles Paxillus involutus.",
      underside: "Not documented.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "Closely resembles the poisonous Paxillus involutus, and is considered likely to also be poisonous. Specific toxins are not documented in the source.",
    lookalikes: [
      {
        name: "Brown roll-rim",
        scientific: "Paxillus involutus",
        danger: "toxic",
        distinguishingFeature: "Paxillus vernalis closely resembles the poisonous Paxillus involutus and is considered likely to also be poisonous."
      }
    ],
    culinary: {
      flavor: "Not documented.",
      preparation: "Considered likely poisonous; not for consumption.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Paxillus vernalis",
        url: "https://en.wikipedia.org/wiki/Paxillus_vernalis"
      },
      {
        name: "iNaturalist — Paxillus vernalis",
        url: "https://www.inaturalist.org/taxa/543037"
      },
      {
        name: "GBIF — Paxillus vernalis",
        url: "https://www.gbif.org/species/5460676"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "ramaria-pallida",
    commonNames: [],
    scientific: "Ramaria pallida",
    family: "Gomphaceae",
    order: "Gomphales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented.",
    habitat: "A coral mushroom found in North America. Further habitat details are not documented in the available sources; occurrence in the Pacific Northwest is Not documented.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented (a coral fungus, lacking a true cap).",
      underside: "Not documented.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "Specific toxins are not documented in the available sources. Pale Ramaria coral fungi are generally regarded as poisonous, typically causing gastrointestinal upset.",
    lookalikes: [],
    culinary: {
      flavor: "Not documented.",
      preparation: "Not recommended for consumption; regarded as toxic.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Ramaria pallida",
        url: "https://en.wikipedia.org/wiki/Ramaria_pallida"
      },
      {
        name: "iNaturalist — Ramaria pallida",
        url: "https://www.inaturalist.org/taxa/847830"
      },
      {
        name: "GBIF — Ramaria pallida",
        url: "https://www.gbif.org/species/5238518"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "russula-nigricans",
    commonNames: [
      "Blackening Brittlegill",
      "Blackening Russula"
    ],
    scientific: "Russula nigricans",
    family: "Russulaceae",
    order: "Russulales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: [
      "conifers"
    ],
    hostTrees: [],
    substrate: "Soil in both deciduous and coniferous woodland, growing under conifer trees.",
    habitat: "A large gilled brittlegill of both deciduous and coniferous woodland, appearing in late summer and autumn under conifer trees across Britain, northern Europe and North America. In North America it appears in the Pacific Northwest and northern California from October to February.",
    elevationM: null,
    regionsPNW: [
      "Western Washington",
      "Western Oregon",
      "Northern California"
    ],
    fruitingMonths: [
      1,
      2,
      9,
      10,
      11,
      12
    ],
    peakMonths: [
      10,
      11
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Dirty white when young, swiftly turning brown and then black on aging; 5-20 cm in diameter, usually with a large depression in the centre of mature caps, which are three-quarter peeling.",
      underside: "Gills are off-white initially, very widely spaced and adnate; they turn red, then grey, and finally black when bruised. The spore print is white, with warty oval spores measuring 7-8 x 6-7 μm.",
      stem: "White, firm and straight, 5-8 cm long and 2-5 cm wide; it too blackens with age.",
      fleshColor: "When cut, turns pale Indian red, then grey, and black within 20 minutes; has a fruity smell.",
      sporePrintColor: "White.",
      odor: "Mild taste with, reportedly, an odor of empty wine barrels; flesh has a fruity smell.",
      sizeCm: "Cap 5-20 cm in diameter; stem 5-8 x 2-5 cm."
    },
    edibility: "toxic",
    toxicityNotes: "Contains toxins that could cause gastrointestinal upset. It is used in pickling, but must be parboiled first. Old specimens are sometimes parasitised by fungi of the genus Asterophora or Nyctalis, in particular Nyctalis parasitica and N. asterophora (the pick-a-back toadstool).",
    lookalikes: [
      {
        name: "Russula acrifolia",
        scientific: "Russula acrifolia",
        danger: "inedible",
        distinguishingFeature: "Also bruises red then black, like R. nigricans."
      },
      {
        name: "Russula dissimulans",
        scientific: "Russula dissimulans",
        danger: "inedible",
        distinguishingFeature: "Also bruises red then black, like R. nigricans."
      },
      {
        name: "Russula albonigra",
        scientific: "Russula albonigra",
        danger: "inedible",
        distinguishingFeature: "Has closer gills and is far less common; bruises directly to black, lacking the red intermediary phase."
      }
    ],
    culinary: {
      flavor: "Mild taste; reportedly an odor of empty wine barrels.",
      preparation: "Used in pickling, but must be parboiled first.",
      preservation: "Used in pickling, but must be parboiled first."
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Russula adusta",
        url: "https://en.wikipedia.org/wiki/Russula_adusta"
      },
      {
        name: "iNaturalist — Russula nigricans",
        url: "https://www.inaturalist.org/taxa/194414"
      },
      {
        name: "GBIF — Russula nigricans",
        url: "https://www.gbif.org/species/7958113"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-22",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; identification/ecology source-derived; conditions are genus/habitat-typical estimates, not field-measured. Wikipedia source page is titled Russula adusta (a closely related blackening brittlegill) while iNaturalist and GBIF index the name Russula nigricans; descriptive detail is drawn from the Wikipedia page as cached."
    }
  },
];
