// AUTO-GENERATED by scripts/lookalikes/codegen-synthesized.mjs. Do not edit by hand.
// PENDING HUMAN REVIEW — toxic/deadly/psychoactive species held out of the live
// catalog. Not imported anywhere until individually approved.
import type { MushroomSpecies } from "../../species-types";

export const PENDING_SPECIES: MushroomSpecies[] = [
  {
    id: "amanita-velatipes",
    commonNames: [
      "Veiled-bulb Amanita",
      "Great Funnel-Veil Amanita"
    ],
    scientific: "Amanita velatipes",
    family: "Amanitaceae",
    order: "Agaricales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented.",
    habitat: "A species of Amanita from eastern North America; it is NOT recorded from the Pacific Northwest.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented.",
      underside: "Not documented.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "Flagged as toxic; specific toxins and effects are not documented in the source.",
    lookalikes: [],
    culinary: {
      flavor: "Not documented.",
      preparation: "Not documented.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Amanita velatipes",
        url: "https://en.wikipedia.org/wiki/Amanita_velatipes"
      },
      {
        name: "iNaturalist — Amanita velatipes",
        url: "https://www.inaturalist.org/taxa/350068"
      },
      {
        name: "GBIF — Amanita velatipes",
        url: "https://www.gbif.org/species/5451757"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "disputed",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); Wikipedia extract is a stub with minimal description and no documented toxins; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "gyromitra-ancilis",
    commonNames: [
      "Pig's ears"
    ],
    scientific: "Gyromitra ancilis",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented",
    habitat: "Not documented",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented",
      underside: "Not documented",
      stem: "Not documented",
      fleshColor: "Not documented",
      sporePrintColor: "Not documented",
      odor: "Not documented",
      sizeCm: "Not documented"
    },
    edibility: "toxic",
    toxicityNotes: "As a Gyromitra species, this fungus is associated with the toxin gyromitrin (which hydrolyses to monomethylhydrazine); it should be treated as toxic and at best edible only when properly cooked. Detailed toxicity data is not documented in the cached sources.",
    lookalikes: [],
    culinary: {
      flavor: "Not documented",
      preparation: "Not documented",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "iNaturalist — Discina ancilis",
        url: "https://www.inaturalist.org/taxa/504623"
      },
      {
        name: "GBIF — Gyromitra ancilis",
        url: "https://www.gbif.org/species/8933807"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-22",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; identification/ecology source-derived; conditions are genus/habitat-typical estimates, not field-measured."
    }
  },
  {
    id: "gyromitra-korfii",
    commonNames: [
      "Not documented"
    ],
    scientific: "Gyromitra korfii",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented (no species-level cached source; only the genus Gyromitra page is available).",
    habitat: "Not documented at the species level in the cached sources. Gyromitra is a genus of about 18 species of ascomycete false morels; species-specific habitat for G. korfii is not documented here.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented at species level; Gyromitra are false morels whose cap is typically convoluted and turban- or brain-like (the genus name derives from gyro, convoluted, and mitra, turban). Members of this gyromitrin-associated false morel group can be mistaken for true morels (Morchella).",
      underside: "Not documented; the convoluted cap surface is the fertile (spore-bearing) layer rather than gills or pores.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "No species-specific toxicity data in the cached sources; assessed from the genus. Some species of Gyromitra are highly poisonous when eaten raw due to the presence of gyromitrin, although some are edible when cooked and Gyromitra spp. are sought after in Scandinavian countries. Widespread hemolysis has been reported from ingestion, which can result in kidney failure; methemoglobinemia has also been seen (typically responsive to methylene blue); and seizures can develop via inhibition of the neurotransmitter GABA. Treated as toxic given the gyromitrin association of the genus, pending species-level review.",
    lookalikes: [
      {
        name: "True morels",
        scientific: "Morchella",
        danger: "edible",
        distinguishingFeature: "Gyromitra are false morels that can be mistaken for the edible true morels (Morchella); the convoluted, turban-like Gyromitra cap differs from the pitted, honeycombed cap of true morels."
      }
    ],
    culinary: {
      flavor: "Not documented.",
      preparation: "Not recommended; some Gyromitra are highly poisonous raw due to gyromitrin, and species-level preparation data for G. korfii is not documented.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Gyromitra (genus)",
        url: "https://en.wikipedia.org/wiki/Gyromitra"
      },
      {
        name: "iNaturalist — Maublancomyces korfii",
        url: "https://www.inaturalist.org/taxa/1613047"
      },
      {
        name: "GBIF — Gyromitra korfii",
        url: "https://www.gbif.org/species/5497497"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "gyromitra-montana",
    commonNames: [
      "Mountain Lorchel",
      "Snow morel (North American)"
    ],
    scientific: "Gyromitra montana",
    family: "Discinaceae",
    order: "Pezizales",
    trophicMode: "saprotrophic",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented in detail; a false morel of the Discina/Gyromitra group that fruits in spring and early summer (snowmelt) in habitats similar to true morels.",
    habitat: "Occurs in North America; described as a very similar, directly related species to the European Discina gigas, from which it apparently differs in having larger spores. As a member of the Discina genus (related to the false morels of Gyromitra), it bears dish- or cup-shaped to convoluted fruit bodies. Species-level distribution within the cached sources notes only North America (Mountain Lorchel); finer PNW localities are not documented.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [
      4,
      5,
      6,
      7
    ],
    peakMonths: [
      5
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented in detail at species level; as a Discina/false-morel relative of Gyromitra the fruit body is dish- or cup-shaped to wrinkled and convoluted (brain-like), resembling true morels. Reportedly very similar to Discina gigas (tannish, wrinkled cap), differing chiefly in spore size.",
      underside: "Not gills: the wrinkled/cup-shaped upper surface is the fertile spore-bearing layer.",
      stem: "Not documented at species level; the related D. gigas has a whitish stalk nearly as thick as the cap.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented; spores apparently larger than those of Discina gigas.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "No species-specific toxin assay in the cached sources. As a Discina relative of the highly toxic false morels of Gyromitra, it is viewed with suspicion (the genus Discina is related to false morels; the best-known member, the pig ear D. ancilis, is deemed edible only after thorough cooking yet viewed with suspicion given the relation to highly toxic false morels). Like the directly related Discina gigas, it is reportedly edible in small amounts only if thoroughly cooked, but eating is not recommended due to similarity to more toxic Gyromitra species. Treated as toxic owing to the gyromitrin-associated false-morel group, pending species-level review.",
    lookalikes: [
      {
        name: "Snow false morel",
        scientific: "Discina gigas",
        danger: "toxic",
        distinguishingFeature: "A very similar and directly related European species; D. montana apparently has larger spores than D. gigas. Both are reportedly edible in small amounts only if thoroughly cooked, but eating is not recommended due to similarity to more toxic mushroom species."
      },
      {
        name: "Pig's ear",
        scientific: "Discina ancilis",
        danger: "edible-when-cooked",
        distinguishingFeature: "The best-known Discina, bearing dish- or cup-shaped fruit bodies; deemed edible after thorough cooking but viewed with suspicion given its relation to the highly toxic false morels."
      },
      {
        name: "True morels",
        scientific: "Morchella",
        danger: "edible",
        distinguishingFeature: "Discina and Gyromitra are false morels related to and resembling true morels; the wrinkled/convoluted or cup-shaped cap differs from the pitted, honeycombed cap of true Morchella."
      }
    ],
    culinary: {
      flavor: "Not documented.",
      preparation: "Reportedly edible in small amounts only if thoroughly cooked, but consumption is not recommended due to similarity to more toxic Gyromitra species.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Discina (fungus)",
        url: "https://en.wikipedia.org/wiki/Discina_(fungus)"
      },
      {
        name: "iNaturalist — Mountain Lorchel (Maublancomyces montanus)",
        url: "https://www.inaturalist.org/taxa/1613046"
      },
      {
        name: "GBIF — Gyromitra montana",
        url: "https://www.gbif.org/species/5497502"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "lactarius-xanthogalactus",
    commonNames: [
      "Yellow-staining Milkcap",
      "Yellow-staining Milk Cap"
    ],
    scientific: "Lactarius xanthogalactus",
    family: "Russulaceae",
    order: "Russulales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Grows on the ground under trees (both conifers and hardwoods). Ectomycorrhizal genus.",
    habitat: "Found on the west coast of the United States, growing on the ground under trees. Fruit bodies grow scattered or in groups under conifers and hardwoods between November and February in Oregon and California.",
    elevationM: null,
    regionsPNW: [
      "Western Oregon",
      "Oregon Coast Range"
    ],
    fruitingMonths: [
      11,
      12,
      1,
      2
    ],
    peakMonths: [
      11,
      12
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Pinkish-cinnamon, measuring 3-11 cm (1.25-4.25 in) wide.",
      underside: "Gills that, with the rest of the mushroom, ooze a white latex when cut or injured that rapidly turns bright sulfur-yellow.",
      stem: "Pinkish-white, 2-6 cm (0.75-2.25 in) long and 0.7-2 cm (0.25-0.75 in) wide.",
      fleshColor: "Exudes white latex that rapidly turns bright sulfur-yellow when cut or injured.",
      sporePrintColor: "Pale yellow.",
      odor: "Not documented.",
      sizeCm: "Cap 3-11 cm wide; stem 2-6 x 0.7-2 cm."
    },
    edibility: "toxic",
    toxicityNotes: "Poisonous. The mushroom has an unpleasant taste. Specific toxins are not documented in the source.",
    lookalikes: [
      {
        name: "Lactarius vinaceorufescens",
        scientific: "Lactarius vinaceorufescens",
        danger: "toxic",
        distinguishingFeature: "Nearly identical microscopic features to L. xanthogalactus, but macroscopically it has reddish-vinaceous stains that develop on the cap, gills, and stem."
      },
      {
        name: "Lactarius colorascens",
        scientific: "Lactarius colorascens",
        danger: "inedible",
        distinguishingFeature: "Distinguished by a smaller fruit body; a whitish cap that becomes brownish-red with age and does not spot vinaceous or brown; bitter to faintly acrid latex; and slightly smaller spores."
      },
      {
        name: "Lactarius chrysorrheus",
        scientific: "Lactarius chrysorrheus",
        danger: "toxic",
        distinguishingFeature: "Has a whitish to pale yellowish-cinnamon cap with slightly darker spots and grows under hardwoods (especially oak) on well-drained, often sandy soil; its gills do not discolor or spot vinaceous or brown."
      },
      {
        name: "Lactarius rubidus",
        scientific: "Lactarius rubidus",
        danger: "edible",
        distinguishingFeature: "Redder and sweet smelling, lacking the yellow staining reaction characteristic of L. xanthogalactus."
      }
    ],
    culinary: {
      flavor: "Unpleasant taste.",
      preparation: "Poisonous; not for consumption.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Lactarius xanthogalactus",
        url: "https://en.wikipedia.org/wiki/Lactarius_xanthogalactus"
      },
      {
        name: "iNaturalist — Lactarius xanthogalactus",
        url: "https://www.inaturalist.org/taxa/118224"
      },
      {
        name: "GBIF — Lactarius xanthogalactus",
        url: "https://www.gbif.org/species/5463015"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "ramaria-pallida",
    commonNames: [],
    scientific: "Ramaria pallida",
    family: "Gomphaceae",
    order: "Gomphales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: null,
    hostTrees: [],
    substrate: "Not documented.",
    habitat: "A coral mushroom found in North America. Further habitat details are not documented in the available sources; occurrence in the Pacific Northwest is Not documented.",
    elevationM: null,
    regionsPNW: [],
    fruitingMonths: [],
    peakMonths: [],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Not documented (a coral fungus, lacking a true cap).",
      underside: "Not documented.",
      stem: "Not documented.",
      fleshColor: "Not documented.",
      sporePrintColor: "Not documented.",
      odor: "Not documented.",
      sizeCm: "Not documented."
    },
    edibility: "toxic",
    toxicityNotes: "Specific toxins are not documented in the available sources. Pale Ramaria coral fungi are generally regarded as poisonous, typically causing gastrointestinal upset.",
    lookalikes: [],
    culinary: {
      flavor: "Not documented.",
      preparation: "Not recommended for consumption; regarded as toxic.",
      preservation: null
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Ramaria pallida",
        url: "https://en.wikipedia.org/wiki/Ramaria_pallida"
      },
      {
        name: "iNaturalist — Ramaria pallida",
        url: "https://www.inaturalist.org/taxa/847830"
      },
      {
        name: "GBIF — Ramaria pallida",
        url: "https://www.gbif.org/species/5238518"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-23",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; PENDING HUMAN REVIEW (deadly/toxic); identification/toxicity source-derived; conditions are genus/habitat-typical estimates."
    }
  },
  {
    id: "russula-nigricans",
    commonNames: [
      "Blackening Brittlegill",
      "Blackening Russula"
    ],
    scientific: "Russula nigricans",
    family: "Russulaceae",
    order: "Russulales",
    trophicMode: "mycorrhizal",
    mycorrhizalPartners: [
      "conifers"
    ],
    hostTrees: [],
    substrate: "Soil in both deciduous and coniferous woodland, growing under conifer trees.",
    habitat: "A large gilled brittlegill of both deciduous and coniferous woodland, appearing in late summer and autumn under conifer trees across Britain, northern Europe and North America. In North America it appears in the Pacific Northwest and northern California from October to February.",
    elevationM: null,
    regionsPNW: [
      "Western Washington",
      "Western Oregon",
      "Northern California"
    ],
    fruitingMonths: [
      1,
      2,
      9,
      10,
      11,
      12
    ],
    peakMonths: [
      10,
      11
    ],
    conditions: {
      minRain7d: 20,
      idealDaysSinceRain: [
        5,
        14
      ],
      tempRangeC: [
        5,
        18
      ],
      humidityMinPct: 80
    },
    identification: {
      cap: "Dirty white when young, swiftly turning brown and then black on aging; 5-20 cm in diameter, usually with a large depression in the centre of mature caps, which are three-quarter peeling.",
      underside: "Gills are off-white initially, very widely spaced and adnate; they turn red, then grey, and finally black when bruised. The spore print is white, with warty oval spores measuring 7-8 x 6-7 μm.",
      stem: "White, firm and straight, 5-8 cm long and 2-5 cm wide; it too blackens with age.",
      fleshColor: "When cut, turns pale Indian red, then grey, and black within 20 minutes; has a fruity smell.",
      sporePrintColor: "White.",
      odor: "Mild taste with, reportedly, an odor of empty wine barrels; flesh has a fruity smell.",
      sizeCm: "Cap 5-20 cm in diameter; stem 5-8 x 2-5 cm."
    },
    edibility: "toxic",
    toxicityNotes: "Contains toxins that could cause gastrointestinal upset. It is used in pickling, but must be parboiled first. Old specimens are sometimes parasitised by fungi of the genus Asterophora or Nyctalis, in particular Nyctalis parasitica and N. asterophora (the pick-a-back toadstool).",
    lookalikes: [
      {
        name: "Russula acrifolia",
        scientific: "Russula acrifolia",
        danger: "inedible",
        distinguishingFeature: "Also bruises red then black, like R. nigricans."
      },
      {
        name: "Russula dissimulans",
        scientific: "Russula dissimulans",
        danger: "inedible",
        distinguishingFeature: "Also bruises red then black, like R. nigricans."
      },
      {
        name: "Russula albonigra",
        scientific: "Russula albonigra",
        danger: "inedible",
        distinguishingFeature: "Has closer gills and is far less common; bruises directly to black, lacking the red intermediary phase."
      }
    ],
    culinary: {
      flavor: "Mild taste; reportedly an odor of empty wine barrels.",
      preparation: "Used in pickling, but must be parboiled first.",
      preservation: "Used in pickling, but must be parboiled first."
    },
    conservationNotes: null,
    sources: [
      {
        name: "Wikipedia — Russula adusta",
        url: "https://en.wikipedia.org/wiki/Russula_adusta"
      },
      {
        name: "iNaturalist — Russula nigricans",
        url: "https://www.inaturalist.org/taxa/194414"
      },
      {
        name: "GBIF — Russula nigricans",
        url: "https://www.gbif.org/species/7958113"
      }
    ],
    autoCompiled: true,
    verification: {
      sourcesAgreeing: 3,
      lastVerified: "2026-06-22",
      consensus: "moderate",
      disputeNotes: "Auto-compiled from Wikipedia/iNaturalist/GBIF; identification/ecology source-derived; conditions are genus/habitat-typical estimates, not field-measured. Wikipedia source page is titled Russula adusta (a closely related blackening brittlegill) while iNaturalist and GBIF index the name Russula nigricans; descriptive detail is drawn from the Wikipedia page as cached."
    }
  },
];
